---

- name: Turn on the LED
  community.cip.ensure_tags:
    tags:
      - name: "LED_Ctrl"
        value: True
- name: Pause for 1 second
  ansible.builtin.pause:
    seconds: 1
- name: Turn on the LED
  community.cip.ensure_tags:
    tags:
      - name: "LED_Ctrl"
        value: False
- name: Pause for 1 second
  ansible.builtin.pause:
    seconds: 1